### ISSUE TITLE
Add thruster as dependency or mention it in README

### ISSUE THREAD

**Issue by K4sku** [evilmartians/capybara-thruster#1]
I wanted to give it a try in a project that does not use thruster (yet) and it did not work out of the box.

I have followed README and rspec started to throw errors with *scary* stack trace at me. When I added the debug option, I got a simple bundler error that no `thrust` is installed and resolved the issue. However, that was not obvious to me at first. 

I know this is a _skill issue_, but I probably won't be the only one to do it 🤷 

My suggestion is to either add thruster as a runtime dependency (which I expected) or add a line in the README.

PS. Thank you for the gem!

Here is a stack error
```
#<Thread:0x0000000128a35ce0 /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/server.rb:76 run> terminated with exception (report_on_exception is true):
/Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 61005 (Errno::EADDRINUSE)
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `new'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `add_tcp_listener'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:163:in `block in parse'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `each'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `parse'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/registrations/servers.rb:63:in `block (2 levels) in <main>'
        from <internal:kernel>:90:in `tap'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/registrations/servers.rb:62:in `block in <main>'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-thruster-0.1.0/lib/capybara/thruster.rb:24:in `block in <main>'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/config.rb:64:in `block in server='
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/server.rb:77:in `block in boot'
#<Thread:0x0000000128adc108 /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/server.rb:76 run> terminated with exception (report_on_exception is true):
/Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 61005 (Errno::EADDRINUSE)
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `new'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `add_tcp_listener'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:163:in `block in parse'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `each'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `parse'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/registrations/servers.rb:63:in `block (2 levels) in <main>'
        from <internal:kernel>:90:in `tap'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/registrations/servers.rb:62:in `block in <main>'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-thruster-0.1.0/lib/capybara/thruster.rb:24:in `block in <main>'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/config.rb:64:in `block in server='
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/server.rb:77:in `block in boot'
F#<Thread:0x0000000128a93bd8 /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/server.rb:76 run> terminated with exception (report_on_exception is true):
/Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 61005 (Errno::EADDRINUSE)
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `new'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `add_tcp_listener'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:163:in `block in parse'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `each'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `parse'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/registrations/servers.rb:63:in `block (2 levels) in <main>'
        from <internal:kernel>:90:in `tap'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/registrations/servers.rb:62:in `block in <main>'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-thruster-0.1.0/lib/capybara/thruster.rb:24:in `block in <main>'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/config.rb:64:in `block in server='
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/server.rb:77:in `block in boot'
#<Thread:0x0000000128b175a0 /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/server.rb:76 run> terminated with exception (report_on_exception is true):
/Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 61005 (Errno::EADDRINUSE)
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `new'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `add_tcp_listener'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:163:in `block in parse'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `each'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `parse'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/registrations/servers.rb:63:in `block (2 levels) in <main>'
        from <internal:kernel>:90:in `tap'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/registrations/servers.rb:62:in `block in <main>'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-thruster-0.1.0/lib/capybara/thruster.rb:24:in `block in <main>'
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/config.rb:64:in `block in server='
        from /Users/cezary/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/capybara-3.40.0/lib/capybara/server.rb:77:in `block in boot'

1st Try error in ./spec/features/multi_location_order_spec.rb:66:
Address already in use - bind(2) for "127.0.0.1" port 61005
undefined method `values_at' for nil:NilClass
```

**Comment by andyjeffries** [comment]
Yeah, agreed - I just started trying this project this morning too, and hit the same issue.

**Comment by palkan** [comment]
Thanks for the report!

We cannot add `truster` as a dependency, 'cause the gem is assumed to be used with alternative `thrust` implementations, too (it's actually extracted from AnyCable Thruster). But we definitely need to handle the lack of `thrust` gracefully.
